/**
 * Type definitions for AI-generated workflows
 *
 * These types represent the structure of workflows generated by OpenAI,
 * which will be transformed into WorkflowNode and WorkflowEdge types.
 */

import type {
  WorkflowNodeType,
  EndNodeStatus,
  ServiceType,
  HttpConfig,
  ConditionConfig,
} from "@/types";

/**
 * Base structure for AI-generated node
 * Contains minimal required fields that will be expanded to full WorkflowNode
 */
export interface GeneratedNode {
  type: WorkflowNodeType;
  title: string;
  description?: string;
  position: { x: number; y: number };

  // Type-specific optional fields
  // EndNode fields
  status?: EndNodeStatus;

  // DecisionNode fields
  condition?: ConditionConfig;

  // ServiceNode fields
  serviceType?: ServiceType;
  http?: HttpConfig;

  // TaskNode fields
  assignee?: string;
}

/**
 * AI-generated edge using array indices instead of node IDs
 * Indices refer to positions in the GeneratedWorkflow.nodes array
 */
export interface GeneratedEdge {
  sourceIndex: number; // Index in nodes array
  targetIndex: number; // Index in nodes array
  sourcePort: string; // Port ID (e.g., "output", "yes", "no")
  targetPort: string; // Port ID (e.g., "input")
}

/**
 * Complete AI-generated workflow response
 */
export interface GeneratedWorkflow {
  nodes: GeneratedNode[];
  edges: GeneratedEdge[];
  metadata: {
    description: string;
    estimatedComplexity: "simple" | "moderate" | "complex";
  };
}

/**
 * Validation result for generated workflows
 */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings?: string[];
}
